# Generated by Django 5.0.1 on 2024-01-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=50)),
                ('genericName', models.CharField(max_length=75)),
                ('cures', models.CharField(max_length=325)),
            ],
        ),
    ]
