# Generated by Django 5.0.1 on 2024-01-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='brandName',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='cures',
            new_name='diseases_cured',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='genericName',
            new_name='generic_name',
        ),
    ]
